apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rhte2023-application-03-hpa
  namespace: rhte2023-application-03
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rhte2023-application-03
  targetCPUUtilizationPercentage: 30
