apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: draw-app
    app.kubernetes.io/instance: draw-app
  name: draw-app
  namespace: draw-app
spec:
  ports:
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app.kubernetes.io/component: draw-app
    app.kubernetes.io/instance: draw-app
status:
  loadBalancer: {}
