apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rhte2023-application-02
    app.kubernetes.io/instance: rhte2023-application-02
  name: rhte2023-application-02
  namespace: rhte2023-application-02
spec:
  ports:
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app.kubernetes.io/component: rhte2023-application-02
    app.kubernetes.io/instance: rhte2023-application-02
status:
  loadBalancer: {}
